import React, { useMemo, useState } from 'react';
import { deleteData, postData, putData } from '../api/client';
import { Field, Money, Badge, EmptyState } from '../components/Common';
import { useApp } from '../state/AppContext';

const initial = { titulo:'', tipo:'departamento', ciudad:'Buenos Aires', pais:'Argentina', direccion:'', precio_noche:50000, cantidad_huespedes:2, descripcion:'', servicios:'wifi,cocina', lat:-34.6, lng:-58.4 };

export default function Anfitrion() {
  const { user, usuarios, propiedades, reservas, run } = useApp();
  const anfitriones = usuarios.filter(u=>u.tipo==='anfitrion');
  const [hostId, setHostId] = useState(user?.tipo === 'anfitrion' ? user.id : '');
  const [form, setForm] = useState(initial);
  const currentHost = user?.tipo === 'anfitrion' ? user.id : hostId;
  const mine = useMemo(()=>propiedades.filter(p=>p.anfitrion_id===currentHost), [propiedades,currentHost]);
  const received = useMemo(()=>reservas.filter(r=>r.anfitrion_id===currentHost), [reservas,currentHost]);
  const create = () => run(() => postData('/propiedades', { anfitrion_id: currentHost, titulo: form.titulo, tipo: form.tipo, ubicacion: { ciudad: form.ciudad, pais: form.pais, direccion: form.direccion, coords: { type:'Point', coordinates:[Number(form.lng), Number(form.lat)] } }, precio_noche: Number(form.precio_noche), cantidad_huespedes: Number(form.cantidad_huespedes), descripcion: form.descripcion, servicios: form.servicios.split(',').map(s=>s.trim()).filter(Boolean) }), 'Propiedad publicada');
  return <div className="stack">
    {user?.tipo !== 'anfitrion' && <section className="panel"><Field label="Trabajar como anfitrión"><select value={hostId} onChange={e=>setHostId(e.target.value)}><option value="">Seleccionar anfitrión</option>{anfitriones.map(a=><option value={a.id} key={a.id}>{a.nombre}</option>)}</select></Field></section>}
    {!currentHost ? <EmptyState title="Elegí un anfitrión" text="Para publicar o administrar propiedades necesitás una sesión de anfitrión o seleccionar uno."/> : <><section className="twoCols"><div className="panel"><h3>Publicar propiedad</h3><Field label="Título"><input value={form.titulo} onChange={e=>setForm({...form,titulo:e.target.value})}/></Field><div className="formGrid"><Field label="Tipo"><select value={form.tipo} onChange={e=>setForm({...form,tipo:e.target.value})}><option>departamento</option><option>casa</option><option>loft</option></select></Field><Field label="Ciudad"><input value={form.ciudad} onChange={e=>setForm({...form,ciudad:e.target.value})}/></Field><Field label="Dirección"><input value={form.direccion} onChange={e=>setForm({...form,direccion:e.target.value})}/></Field><Field label="Precio por noche"><input type="number" value={form.precio_noche} onChange={e=>setForm({...form,precio_noche:e.target.value})}/></Field><Field label="Capacidad"><input type="number" value={form.cantidad_huespedes} onChange={e=>setForm({...form,cantidad_huespedes:e.target.value})}/></Field><Field label="Servicios"><input value={form.servicios} onChange={e=>setForm({...form,servicios:e.target.value})}/></Field></div><Field label="Descripción"><textarea value={form.descripcion} onChange={e=>setForm({...form,descripcion:e.target.value})}/></Field><button onClick={create}>Publicar</button></div><div className="panel"><h3>Reservas recibidas</h3>{received.length ? received.map(r=><div className="miniItem" key={r.id}><div className="dateBox">{r.fecha_inicio.slice(5)}</div><div><b>{r.propiedad?.titulo}</b><p>{r.huesped?.nombre} · {r.estado} · <Money value={r.pago.monto}/></p></div></div>) : <p className="muted">Todavía no recibiste reservas.</p>}</div></section><section><h3>Mis propiedades</h3><div className="cardsGrid compact">{mine.length ? mine.map(p=><article className="propertyCard" key={p.id}><img src={p.imagen}/><div className="propertyBody"><h3>{p.titulo}</h3><p>{p.ubicacion.ciudad} · <Money value={p.precio_noche}/> · máx {p.cantidad_huespedes}</p><Badge>{p.estado}</Badge><div className="row"><button onClick={()=>run(()=>putData(`/propiedades/${p.id}`,{precio_noche:Number(p.precio_noche)+5000}),'Precio actualizado')}>Subir $5000</button><button className="danger" onClick={()=>run(()=>deleteData(`/propiedades/${p.id}`),'Propiedad eliminada')}>Eliminar</button></div></div></article>) : <EmptyState title="Sin propiedades" text="Publicá la primera propiedad desde el formulario."/>}</div></section></>}
  </div>;
}
