import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { getData, postData, putData, patchData, deleteData } from './api/client';
import './styles.css';

function App(){
  const [usuarios,setUsuarios]=useState([]), [user,setUser]=useState(null), [props,setProps]=useState([]), [reservas,setReservas]=useState([]), [msg,setMsg]=useState(''), [filters,setFilters]=useState({});
  const [tab,setTab]=useState('propiedades');
  const load=async()=>{ setUsuarios(await getData('/usuarios')); setProps(await getData('/propiedades',{params:filters})); setReservas(await getData('/reservas')); };
  useEffect(()=>{load()},[]);
  const run=async(fn,ok='Listo')=>{try{await fn(); setMsg(ok); await load();}catch(e){setMsg(e.response?.data?.message||e.message)}};
  const anfitriones=usuarios.filter(u=>u.tipo==='anfitrion'), huespedes=usuarios.filter(u=>u.tipo==='huesped');
  return <main>
    <header><h1>AirBnB TPO</h1><p>Login simulado + acciones funcionales del enunciado</p></header>
    {msg && <div className="msg">{msg}<button onClick={()=>setMsg('')}>x</button></div>}
    <section className="card login"><h2>Login simulado</h2><select onChange={e=>setUser(usuarios.find(u=>u.id===e.target.value))} value={user?.id||''}><option value="">Seleccionar usuario</option>{usuarios.map(u=><option key={u.id} value={u.id}>{u.nombre} - {u.tipo}</option>)}</select>{user&&<b>Logueado como {user.nombre}</b>}</section>
    <nav>{['propiedades','reservas','usuarios','resenias'].map(t=><button className={tab===t?'active':''} onClick={()=>setTab(t)} key={t}>{t}</button>)}</nav>
    {tab==='propiedades'&&<Propiedades user={user} props={props} anfitriones={anfitriones} filters={filters} setFilters={setFilters} search={()=>run(async()=>setProps(await getData('/propiedades',{params:filters})),'Búsqueda aplicada')} run={run}/>} 
    {tab==='reservas'&&<Reservas reservas={reservas} props={props} huespedes={huespedes} user={user} run={run}/>} 
    {tab==='usuarios'&&<Usuarios usuarios={usuarios} run={run}/>} 
    {tab==='resenias'&&<Resenias reservas={reservas} props={props} run={run}/>} 
  </main>
}
function Propiedades({user,props,anfitriones,filters,setFilters,search,run}){
 const [f,setF]=useState({titulo:'',tipo:'departamento',anfitrion_id:'',ciudad:'',pais:'Argentina',direccion:'',precio_noche:50000,cantidad_huespedes:2,descripcion:'',servicios:'wifi'});
 return <section className="grid"><div className="card"><h2>Buscar propiedades</h2>{['ciudad','tipo','precioMax','lat','lng','radioKm'].map(k=><input key={k} placeholder={k} onChange={e=>setFilters({...filters,[k]:e.target.value})}/>) }<button onClick={search}>Buscar</button></div>
 <div className="card"><h2>Publicar propiedad</h2><select value={f.anfitrion_id} onChange={e=>setF({...f,anfitrion_id:e.target.value})}><option value="">Anfitrión</option>{anfitriones.map(a=><option key={a.id} value={a.id}>{a.nombre}</option>)}</select>{['titulo','tipo','ciudad','direccion','precio_noche','cantidad_huespedes','descripcion','servicios'].map(k=><input key={k} placeholder={k} value={f[k]} onChange={e=>setF({...f,[k]:e.target.value})}/>)}<button onClick={()=>run(()=>postData('/propiedades',{...f,ubicacion:{ciudad:f.ciudad,pais:f.pais,direccion:f.direccion,coords:{type:'Point',coordinates:[-58.4,-34.6]}},servicios:f.servicios.split(',').map(x=>x.trim())}),'Propiedad creada')}>Crear</button></div>
 <div className="wide list">{props.map(p=><article className="card" key={p.id}><h3>{p.titulo}</h3><p>{p.tipo} · {p.ubicacion.ciudad} · ${p.precio_noche}/noche · máx {p.cantidad_huespedes} huéspedes</p><p>{p.descripcion}</p><p>Servicios: {p.servicios.join(', ')} · Rating: {p.promedio_rating}</p><button onClick={()=>run(()=>putData('/propiedades/'+p.id,{precio_noche:Number(p.precio_noche)+5000}),'Precio actualizado')}>Subir precio +5000</button><button className="danger" onClick={()=>run(()=>deleteData('/propiedades/'+p.id),'Propiedad eliminada')}>Eliminar</button></article>)}</div></section>
}
function Reservas({reservas,props,huespedes,user,run}){
 const [f,setF]=useState({huesped_id:'',propiedad_id:'',fecha_inicio:'2026-06-01',fecha_fin:'2026-06-05',cantidad_huespedes:2,metodo:'tarjeta'});
 return <section className="grid"><div className="card"><h2>Crear reserva</h2><select value={f.huesped_id} onChange={e=>setF({...f,huesped_id:e.target.value})}><option value="">Huésped</option>{huespedes.map(h=><option key={h.id} value={h.id}>{h.nombre}</option>)}</select><select value={f.propiedad_id} onChange={e=>setF({...f,propiedad_id:e.target.value})}><option value="">Propiedad</option>{props.map(p=><option key={p.id} value={p.id}>{p.titulo}</option>)}</select>{['fecha_inicio','fecha_fin','cantidad_huespedes'].map(k=><input key={k} type={k.includes('fecha')?'date':'number'} value={f[k]} onChange={e=>setF({...f,[k]:e.target.value})}/>) }<select value={f.metodo} onChange={e=>setF({...f,metodo:e.target.value})}><option>tarjeta</option><option>transferencia</option><option>efectivo</option></select><button onClick={()=>run(()=>postData('/reservas',{...f,pago:{metodo:f.metodo,estado:'pendiente'}}),'Reserva creada')}>Confirmar reserva</button></div><div className="wide list">{reservas.map(r=><article className="card" key={r.id}><h3>{r.propiedad?.titulo}</h3><p>Huésped: {r.huesped?.nombre} · Estado: <b>{r.estado}</b></p><p>{r.fecha_inicio} al {r.fecha_fin} · {r.cantidad_huespedes} huéspedes</p><p>Pago: ${r.pago.monto} · {r.pago.metodo} · {r.pago.estado}</p><button onClick={()=>run(()=>patchData('/reservas/'+r.id+'/finalizar'),'Reserva finalizada')}>Finalizar</button><button className="danger" onClick={()=>run(()=>patchData('/reservas/'+r.id+'/cancelar'),'Reserva cancelada')}>Cancelar</button></article>)}</div></section>
}
function Usuarios({usuarios,run}){const [f,setF]=useState({nombre:'',email:'',telefono:'',tipo:'huesped'});return <section className="grid"><div className="card"><h2>Crear usuario</h2>{['nombre','email','telefono'].map(k=><input key={k} placeholder={k} onChange={e=>setF({...f,[k]:e.target.value})}/>) }<select onChange={e=>setF({...f,tipo:e.target.value})}><option value="huesped">huesped</option><option value="anfitrion">anfitrion</option></select><button onClick={()=>run(()=>postData('/usuarios',f),'Usuario creado')}>Crear</button></div><div className="wide list">{usuarios.map(u=><article className="card" key={u.id}><h3>{u.nombre}</h3><p>{u.email} · {u.tipo} · rating {u.promedio_rating}</p><button onClick={()=>run(()=>putData('/usuarios/'+u.id,{telefono:'actualizado'}),'Usuario actualizado')}>Actualizar teléfono demo</button></article>)}</div></section>}
function Resenias({reservas,props,run}){const [f,setF]=useState({reserva_id:'',calificacion:5,comentario:''}); const completadas=reservas.filter(r=>r.estado==='completada');return <section className="grid"><div className="card"><h2>Crear reseña</h2><select onChange={e=>setF({...f,reserva_id:e.target.value})}><option value="">Reserva completada</option>{completadas.map(r=><option key={r.id} value={r.id}>{r.propiedad?.titulo} - {r.huesped?.nombre}</option>)}</select><input type="number" min="1" max="5" value={f.calificacion} onChange={e=>setF({...f,calificacion:e.target.value})}/><textarea placeholder="comentario" onChange={e=>setF({...f,comentario:e.target.value})}/><button onClick={()=>run(()=>postData('/resenias',f),'Reseña creada')}>Publicar reseña</button></div><div className="wide list">{props.map(p=><ReviewBox key={p.id} p={p}/>)}</div></section>}
function ReviewBox({p}){const [rs,setRs]=useState([]);useEffect(()=>{getData('/propiedades/'+p.id+'/resenias').then(setRs)},[p.id,p.promedio_rating]);return <article className="card"><h3>{p.titulo} · rating {p.promedio_rating}</h3>{rs.length===0?<p>Sin reseñas</p>:rs.map(r=><p key={r.id}>⭐ {r.calificacion}: {r.comentario}</p>)}</article>}

createRoot(document.getElementById('root')).render(<App/>);
